### ISSUE TITLE
Statements with same text should not be highlighted together

### ISSUE THREAD

**Issue by tlatoza** [devuxd/ProgrammingStrategies#30]
The active statement is highlighted based on its text. If multiple statements have identical text, they are both highlighted, resulting in a situation where there are multiple statements that appear to the user to be active:

![image](https://user-images.githubusercontent.com/1881771/34440592-13dada96-ec84-11e7-8737-68dd065df121.png)

**Comment by MaryamArab** [comment]
Fixed
