### ISSUE TITLE
Next button should be enabled after text is entered for variable

### ISSUE THREAD

**Issue by tlatoza** [devuxd/ProgrammingStrategies#32]
After the user is prompted to set the value of a variable and types a value into the text box, the user moves the cursor to click the next button. However, the next button is not yet enabled:

![image](https://user-images.githubusercontent.com/1881771/34440664-aa03a188-ec84-11e7-9c61-30a7093a00e1.png)

In this case, the user is unsure what they need to do to make progress: they've followed the directions, and still cannot click next.

Clicking elsewhere (so that the textbox loses focus) will solve the issue, but this is not discoverable. The next button should be enabled as soon as the user enters text in the textbox.

**Comment by MaryamArab** [comment]
Fixed
